# TRAEFIK MINI
# replace <values> (remove <>)

services:

  traefik:
    image: traefik:latest
    container_name: "traefik-mini"
    command:
      - "--log.level=<INFO>" # <INFO || DEBUG>
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    networks:
      - <network> # deocker network name - needs to be the same for all containers and DNS-Proxy-Server
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # access to dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

# test application
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    hostname: "whoami"
    networks:
      - <network> # deocker network name - needs to be the same for all containers and DNS-Proxy-Server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`<url>`)" # eg <'whoami.vserver04.lan'>
      - "traefik.http.routers.whoami.entrypoints=web"
      # - "dns.hostname=whoami" not sure this is needed

networks:
  <dns>: # deocker network name - needs to be the same for all containers and DNS-Proxy-Server
    external: true
